services:
  - type: web
    name: doctors-ngn-backend
    runtime: ruby
    plan: free
    buildCommand: ./bin/render-build.sh && (bundle exec rails db:prepare || (echo "Trying db:schema:load"; DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rails db:schema:load))
    startCommand: bundle exec rails server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: common_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
