databases:
  - name: common_db # Ensure the actual name matches with render db
    databaseName: common_db_c8vl  # Ensure the actual name matches here
    user: common_db_c8vl_user
    plan: free
services:
  - type: web
    name: doctors-ngn-backend # Use the correct name for your web service here
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh && bundle exec rails db:schema:load"
    startCommand: "bundle exec rails server"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: common_db  # This matches the `name` under `databases`
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
