default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medic-bd-dev
  user: <%= Rails.application.credentials.dig(:development, :database_user) %>
  password: <%= Rails.application.credentials.dig(:development, :database_password) %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
 