default: &default
  adapter: postgresql
  encoding: unicode

  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medic_bd_dev
  username: <%= ENV['DB_USER'] || Rails.application.credentials.dig(:development, :database_user) || ENV['USER'] %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials.dig(:development, :database_password) %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  schema_search_path: medicbd, public

test:
  <<: *default
  database: medic_bd_test
  username: <%= ENV['DB_USER'] || Rails.application.credentials.dig(:test, :database_user) || ENV['USER'] %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials.dig(:test, :database_password) %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  schema_search_path: medicbd, public
  

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  schema_search_path: medicbd, public
